---
sidebar: docs_sidebar
permalink: concept_vcp_product_overview.html
summary:
keywords: netapp, vcp, element, vcenter plugin, plug-in
---

= NetApp Element Plug-in for vCenter Server product overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, vcp, element, vcenter plugin, plug-in

[.lead]
The NetApp Element Plug-in for vCenter Server (VCP) is a web-based tool integrated with the VMware vSphere Web Client user interface (UI). The plug-in is an extension and alternative scalable, user-friendly interface for VMware vSphere that can manage and monitor storage clusters running *NetApp Element software* software.

You can use the plug-in user interface to discover and configure clusters, and to manage, monitor, and allocate storage from cluster capacity to configure datastores and virtual datastores (for virtual volumes). A cluster appears on the network as a single local group that is represented to hosts and administrators by virtual IP addresses. You can also monitor cluster activity with real-time reporting, including error and alert messaging for any event that might occur while performing various operations.

== NetApp components related to the plug-in

* *Registration utility*: A tool that allows you to manage the link:vcp_concept_vvols.html[QoSSIOC] service and plug-in registration with vCenter.

* *Management services*: Microservices that include the QoSSIOC service for the vCenter Plug-in. Upgrades to the plug-in are released as part of a management services bundle.
+
TIP: Learn more about link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[management services releases].

* *Management node (mNode)*: A virtual machine that runs in parallel with one or more Element software-based storage clusters. As of the Element 11.3 release, management services are hosted on the management node, allowing for quicker updates of select software services outside of major releases.

== Common URLs
In addition to vSphere, these are some of the common URLs you use with vCenter plug-in:

[%header,cols=2*]
|===
|URL
|Description


|`https://[management node IP address]:9443`
|Register the vCenter Plug-in package in the vSphere Web Client.

|`https://[management node IP address]:442`
|From the management node per-node UI, access network and cluster settings and utilize system tests and utilities. https://docs.netapp.com/us-en/hci/docs/task_mnode_access_ui.html[Learn more.]

|`https://[management node IP address]`
|Access NetApp Hybrid Cloud Control to upgrade your management services, or expand, monitor, and manage your installation. link:task_hci_getstarted.html[Learn more.]

|`https://[management node IP address]/mnode`
|Manually update management services or manage assets using the REST API UI from the management node. https://docs.netapp.com/us-en/hci/docs/task_mnode_access_ui.html[Learn more.]

|`https://[storage cluster MVIP address]`
|Access the NetApp Element software UI.
|===

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
