---
sidebar: sidebar
permalink: reference_requirements_vcp.html
summary: Before you begin using the NetApp Element Plug-in for VMware vCenter Server, you need to understand prerequisites for product installation and use.
keywords: netapp, hci, kubernetes, on premise, cloud services
---

= Requirements for the NetApp Element Plug-in for VMware vCenter Server
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you use NetApp Element Plug-in for VMware vCenter Server to manage your NetApp HCI or SolidFire all-flash array storage, you must verify that your system meets the requirements for plug-in use.

[role="tabbed-block"] 
==== 
.Element vCenter Plug-in 5.0 or later
-- 
Verify that your system meets the requirements for use of Element vCenter Plug-in 5.0 or later.

.VMware vSphere prerequisites
VMware vSphere 8.0 and 7.0 including vCenter and ESXi with software iSCSI adapter and iSCSI networking configured, is required to use the Element vCenter Plug-in.

.VMware vSphere versions supported by the plug-in
The plug-in supports the following major versions of VMware software:

* vSphere 8.0 including vCenter Server, ESXi, and VMFS5 and VMFS6 datastores
* vSphere 7.0 and 7.0 Update 1, 2 and 3 including vCenter Server, ESXi, and VMFS5 and VMFS6 datastores

IMPORTANT: VMware vSphere 6.5 and 6.7 reached end of support status on October 15, 2022. Beginning with Element Plug-in 5.0, vSphere 6.5 and 6.7 are no longer supported. For details, see this https://core.vmware.com/blog/reminder-vsphere-6567-end-general-support[article^].
--

.Element vCenter Plug-in 4.10 or earlier
-- 
Verify that your system meets the requirements for use of Element vCenter Plug-in 4.10 or earlier.

.VMware vSphere prerequisites
VMware vSphere 7.0, 6.7, or 6.5 including vCenter and ESXi with software iSCSI adapter and iSCSI networking configured, is required to use the Element vCenter Plug-in.

.VMware vSphere versions supported by the plug-in
The plug-in supports the following major versions of VMware software:

* vSphere 7.0 and 7.0 Update 1 and 2 including vCenter Server, ESXi, and VMFS5 and VMFS6 datastores
* vSphere 7.0 Update 3 including vCenter Server, ESXi, and VMFS5 and VMFS6 datastores using Spring Framework 4
+
IMPORTANT: When you upgrade to VMware vCenter Server 7.0 U3, the Element Plug-in fails to deploy. To resolve this issue using Spring Framework 4, see https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/vCenter_plug-in_deployment_fails_after_upgrading_vCenter_to_version_7.0_U3[this KB article^].

* vSphere 6.7 and 6.7 Update 1 and 3, including vCenter Server, ESXi, and VMFS5 and VMFS6 datastores
+
IMPORTANT: The plug-in is not compatible with version 6.7 U2 build 13007421 of the HTML5 vSphere Web Client and other 6.7 U2 builds released prior to update 2a (build 13643870). It is compatible with the version 6.7 U2 vSphere Web Client for Flash/FLEX.

* vSphere 6.5, including vCenter Server, ESXi, and VMFS5 and VMFS6 datastores
+
IMPORTANT: The plug-in is not compatible with version 6.5 for Element Plug-in for VMware vCenter Server 4.6, 4.7, and 4.8.

.End of vSphere 6.0 support

IMPORTANT: VMware vSphere 6.0 reached end of support status on March 12, 2020. Beginning with NetApp HCI 1.8 and Element 12, vSphere 6.0 is no longer supported. For details, see this https://mysupport.netapp.com/info/communications/ECMLP2863840.html[product communiqué].
--
====

== vSphere compatibility and best practices
Consider the following capabilities and recommendations before using the plugin:

* vCenter high availability (VCHA) is not supported.
* Because datastores are created using the highest VMFS version supported by the selected ESXi host, all cluster members should run the same version of vSphere and ESXi to avoid VMFS compatibility issues.
* The vSphere HTML5 Web Client and Flash Web Client have separate databases that cannot be combined. Clusters added in one client will not be visible in the other. If you intend to use both clients, add your clusters in both.

== NetApp Element support
The plug-in supports the following major versions:

* Element 12.x
* Element 11.x

== Network port requirements
You need to allow some TCP ports through your datacenter's edge firewall so that you can manage the system remotely and allow clients outside of your datacenter to connect to resources. For a comprehensive list of ports used in NetApp HCI and SolidFire systems, see this link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html[page].

== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
*	https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
