---
sidebar: docs_sidebar
permalink: reference_requirements_vcp.html
summary: Before you begin using the NetApp Element Plug-in for vCenter Server, you need to understand prerequisites for product installation and use.
keywords: netapp, hci, kubernetes, on premise, cloud services
---

= Requirements for the Element Plug-in for vCenter Server
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you use NetApp Element Plug-in for vCenter Server to manage your NetApp HCI or SolidFire all-flash array storage, you need to be sure that your system meets the requirements for plug-in use.​

== VMware vSphere prerequisites
VMware vSphere 7.0, 6.7, or 6.5, including vCenter and ESXi with software iSCSI adapter and iSCSI networking configured, is required to use the NetApp Element Plug-in for vCenter Server. To learn more, see the https://library.netapp.com/ecm/ecm_download_file/ECMLP2874631[release notes].

== vSphere compatibility and best practices
Consider the following capabilities and recommendations before using the plugin:

* The plug-in supports vSphere 7.0. The plug-in is not compatible with vSphere 7.0 U1.
* The plug-in is not compatible with version 6.7 U2 of the HTML5 vSphere Web Client.
* The plug-in supports version 6.7 U2 vSphere Web Client for Flash/FLEX and the vSphere 6.7 U3 release for both Flash and HTML5 clients.
* vCenter high availability (VCHA) is not supported.
* Because datastores are created using the highest VMFS version supported by the selected ESXi host, all cluster members should run the same version of vSphere and ESXi to avoid VMFS compatibility issues.
* The vSphere HTML5 Web Client and Flash Web Client have separate databases that cannot be combined. Clusters added in one client will not be visible in the other. If you intend to use both clients, add your clusters in both.

== Network port requirements
You need to allow some TCP ports through your datacenter's edge firewall so that you can manage the system remotely and allow clients outside of your datacenter to connect to resources. For a comprehensive list of ports used in NetApp HCI and SolidFire systems, see this link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html[page].

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
