---
sidebar: sidebar
permalink: rn_whatsnew_vcp.html
summary: Learn what's new in this version of NetApp Element Plug-in for VMware vCenter Server.
keywords: netapp, vcp, vcenter, plugin, element, new, whats new
---
= What's new in NetApp Element Plug-in for VMware vCenter Server
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Element Plug-in for vCenter Server 5.3 provides security and performance improvements. https://library.netapp.com/ecm/ecm_download_file/ECMLP3316480[Learn more^].

Element vCenter plug-in 5.3 is available with the 2.25.40 release of management services.

== NetApp Element Plug-in for vCenter Server 5.2
NetApp Element Plug-in for vCenter Server 5.2 contains supportability improvements and an enhancement to the custom Protection Domains display. 

With version 5.2, the plug-in displays the Custom Protection Domain Health information when a custom Protection Domain is configured on an Element software cluster. link:vcp_task_reports_overview.html#reporting-overview-page-data[Learn more].

Element vCenter plug-in 5.2 is available with the 2.24.40 release of management services.

== NetApp Element Plug-in for vCenter Server 5.1
NetApp Element Plug-in for vCenter Server 5.1 provides security and performance improvements. https://library.netapp.com/ecm/ecm_download_file/ECMLP2885734[Learn more^].

== NetApp Element Plug-in for vCenter Server 5.0
NetApp Element Plug-in for vCenter Server 5.0 contains the remote plug-in architecture which is designed to integrate the plug-in functionality into a vSphere Client without having to run inside the vCenter Server. The remote architecture supports plug-in isolation and enables scale-out of plug-ins that operate in large vSphere environments. The remote Element Plug-in is deployed in a docker container inside a management node along with management services. link:vcp_concept_remote_plugin_architecture.html[Learn more]. 

Element vCenter plug-in 5.0 supports VMware vSphere 8.0, 7.0, and 7.0 Update 1, 2 and 3 including vCenter Server, ESXi, and vSphere HTML5 Web Client.

Element vCenter plug-in 5.0 is available with the 2.22.7 release of management services. If you do not use the plug-in, this is an optional upgrade because all other services and functionalities are identical to version 2.21.61. For information on the latest management services updates, see https://library.netapp.com/ecm/ecm_download_file/ECMLP2884458[Management Services Release Notes 2.21.61^].

== NetApp Element Plug-in for vCenter Server 4.10
Element vCenter plug-in 4.10 contains resolved issues, including security vulnerabilities, that might significantly reduce disruptions seen during upgrades and enhance daily operation in some environments. In version 4.10 of the plug-in, the online help links have transitioned to this link:index.html[documentation link]. To access the online help links from within the plug-in, you must have network access. 

Element vCenter plug-in 4.10 is available with the 2.21.61 release of management services.

== NetApp Element Plug-in for vCenter Server 4.9
NetApp Element Plug-in for vCenter Server 4.9 restores support for vSphere 6.5, including vCenter Server, ESXi, and vSphere HTML5 Web Client.

Element vCenter plug-in 4.9 is available with the 2.20.69 release of management services.

== NetApp Element Plug-in for vCenter Server 4.8
Element vCenter plug-in 4.8 contains security improvements, memory utilization improvements, and third-party library upgrades.

Element vCenter plug-in 4.8 is available with the 2.19 release of management services.

== NetApp Element Plug-in for vCenter Server 4.7
Element vCenter plug-in 4.7 contains important security improvements that further develop improvements made in the https://security.netapp.com/advisory/ntap-20210315-0001/[recent management services 2.17.56 patch] release.

With version 4.7, the plug-in now supports components of vSphere 7.0 Update 2, including vCenter Server, ESXi, and vSphere HTML5 Web Client.

Element vCenter plug-in 4.7 is available with the 2.18 release of management services.

== NetApp Element Plug-in for vCenter Server 4.6
With version 4.6, the plug-in now supports components of vSphere 7.0 Update 1, including vCenter Server, ESXi, and vSphere HTML5 Web Client.

Element vCenter plug-in 4.6 is available with the 2.16 release of management services.

== Find more information
* link:reference_earlier_versions.html[Earlier versions of NetApp Element Plug-in documentation]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[Hybrid Cloud Control and Management Services Release Notes KB^]
* https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]

// 2022 FEB 03, DOC-4651