---
sidebar: sidebar
permalink: vcp_task_protect_snapshots_volume.html
summary: You can ensure copies of your data are created and stored where you need them.
keywords: netapp, hci, vcp, vcenter, element, protect, snapshots, clone, backup, amazon, s3, openstack, swift
---

= Create and manage volume snapshots in vCenter Server
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Creating a volume snapshot creates a point-in-time copy of a volume. The process takes only a small amount of system resources and space, which makes snapshot creation faster than cloning.

You can use snapshots to roll a volume back to the state it was in at the time the snapshot was created. However, because snapshots are simply replicas of volume metadata, you cannot mount or write to them.

Subsequently, you can back up a volume snapshot to an Amazon S3 object store, an OpenStack Swift object store, or a cluster running NetApp Element software.

You can replicate snapshots to a remote NetApp Element cluster and use them as a backup copy for the volume. This enables you to roll back a volume to a specific point in time by using the replicated snapshot; you can also create a clone of a volume from a replicated snapshot.

Using the vCenter Plug-in, you can create and manage volume snapshots by completing the following tasks:

* <<Create a volume snapshot>>
* <<View volume snapshot details>>
* <<Clone a volume from a snapshot>>
* <<Roll back a volume to a snapshot>>
* <<Back up a volume snapshot to an external object store>>
* <<Delete a volume snapshot>>


== Create a volume snapshot
You can create a snapshot of an active volume to preserve the volume image at any point in time. You can create up to 32 snapshots for a single volume.

.Steps

. From the vCenter Plug-in, select *NetApp Element Management* > *Management*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *Volumes* sub-tab.
. From the Active view, check the volume to use for the snapshot.
. Click *Actions*.
. In the resulting menu, select *Create Snapshot*.
. *Optional*: In the Create Snapshot dialog box, enter a name for the snapshot.
+
TIP: Use descriptive naming best practices. This is especially important if multiple clusters or vCenter Servers are used in your environment. If you do not enter a name, the system creates a snapshot default name using the date and time that the snapshot was created.

. *Optional*: Select the *Include snapshot in replication when paired* check box to ensure that the snapshot is replicated when the parent volume is paired.

. Select one of the following as the retention period for the snapshot:
+
* *Keep forever*: Retains the snapshot on the system indefinitely.
* *Set retention period*: Determine a length of time (days, hours, or minutes) for the system to retain the snapshot.
+
NOTE: When you set a retention period, you select a period that begins at the current time. (Retention is not calculated from the snapshot creation time.)

. To take a single, immediate snapshot, select *Take snapshot now*.
. To schedule the snapshot to run at a future time, complete the following steps:
.. Select *Create snapshot schedule*.
.. Enter a schedule name.
.. Select a schedule type and configure the schedule details.
.. *Optional*: Check *Recurrent Schedule* to repeat the scheduled snapshot periodically.
. Click *OK*.

== View volume snapshot details

You might want to verify that the snapshot was added.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *Snapshots* sub-tab.
. *Optional*: Select one of the following filters:
+
* *Individual*: Volume snapshots that are not members of a group snapshot.
* *Members*: Volume snapshots that are members of a group snapshot.
* *Inactive*: Volume snapshots that were created from volumes that have been deleted but not yet purged.

. View the snapshot details:
+
* *Volume size*: Size of the volume from which the volume was created.
* *Create date*: The date and time when the snapshot was created.
* *Expiration date*: The day and time when the snapshot will be deleted as defined by the retention period.
* *Group Snapshot ID*: If the snapshot is grouped together with other volume snapshots, the ID of the group.
* *Remote Replication*: Identifies whether or not the snapshot is enabled for replication to a remote cluster running NetApp Element software.
** *True*: The snapshot is enabled for remote replication.
** *False*: The snapshot is not enabled for remote replication.
* *Remote Status*: Displays the status of the snapshot on the remote cluster running NetApp Element software:
** *Present*: The snapshot exists on a remote cluster.
** *Not Present*: The snapshot doesn't exist on a remote cluster.
** *Syncing*: The target cluster is currently replicating the snapshot.
** *Deleted*: The target replicated the snapshot and then deleted it.

== Clone a volume from a snapshot
You can create a new volume from a snapshot of a volume. When you do this, the system uses the snapshot information to clone a new volume using the data contained on the volume at the time the snapshot was created. This process also stores information about other snapshots of the volume in the new created volume.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *Snapshots* sub-tab.
. Select one of two views:
+
* *Individual*: Lists volume snapshots that are not members of a group snapshot.
* *Members*: Lists volume snapshots that are members of a group snapshot.
. Check the volume snapshot to clone as a volume.
. Click *Actions*.
. In the resulting menu, select *Clone Volume from Snapshot*.
. Enter a volume name, the total size and select either GB or GiB for the new volume.
. Select an access type for the volume:
+
* *Read Only*: Only read operations are allowed.
* *Read/Write*: Both read and write operations are allowed.
* *Locked*: No read or write operations are allowed.
* *Replication Target*: Designated as a target volume in a replicated volume pair.
. Select a user account to associate with the new volume.
. Click *OK*.
. Validate the new volume:
.. Select *NetApp Element Management* > *Management*.
.. Click the *Volumes* sub-tab.
.. From the *Active* view, confirm that the new volume is listed.
+
TIP: Refresh the page if needed.

== Roll back a volume to a snapshot
You can roll back a volume to a snapshot at any time. This undoes any changes made to the volume since the snapshot was created.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *Snapshots* sub-tab.
. Select one of two views:
+
* *Individual*: Lists volume snapshots that are not members of a group snapshot.
* *Members*: Lists volume snapshots that are members of a group snapshot.
. Check the volume snapshot to use for the volume rollback.
. Click *Actions*.
. In the resulting menu, select *Rollback Volume to Snapshot*.
. *Optional*: To save the current state of the volume before rolling back to the snapshot:
+
.. In the Rollback to Snapshot dialog box, select *Save volume's current state as a snapshot*.
.. Enter a name for the new snapshot.
. Click *OK*.



== Back up a volume snapshot to an external object store
You can use the integrated backup feature to back up a volume snapshot. You can back up snapshots from a cluster running NetApp Element software to an external object store or to another Element-based cluster.

When you back up a snapshot to an external object store, you must have a connection to the object store that allows read/write operations.

* <<Back up a volume snapshot to an Amazon S3 object store>>
* <<Back up a volume snapshot to an OpenStack Swift object store>>
* <<Back up a volume snapshot to a cluster running Element software>>

=== Back up a volume snapshot to an Amazon S3 object store
You can back up NetApp Element snapshots to external object stores that are compatible with Amazon S3.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *Snapshots* sub-tab.
. Check the volume snapshot you want to back up.
. Click *Actions*.
. In the resulting menu, select *Backup to*.
. In the dialog under *Back up volume to*, select *Amazon S3*.
. Select an option under with the following data format:
+
* *Native*: A compressed format readable only by NetApp Element software-based storage systems.
* *Uncompressed*: An uncompressed format compatible with other systems.

. Enter the details:
+
* *Host name*: Enter a host name to use to access the object store.
* *Access key ID*: Enter an access key ID for the account.
* *Secret access key*: Enter the secret access key for the account.
* *Amazon S3 Bucket*: Enter the S3 bucket in which to store the backup.
* *Prefix*: (Optional) Enter a prefix for the backup name.
* *Nametag*: (Optional) Enter a nametag to append to the prefix.
. Click *OK*.

=== Back up a volume snapshot to an OpenStack Swift object store
You can back up NetApp Element snapshots to secondary object stores that are compatible with OpenStack Swift.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *Snapshots* sub-tab.
. Check the volume snapshot you want to back up.
. Click *Actions*.
. In the resulting menu, select *Backup to*.
. In the dialog under *Back up volume to*, select *OpenStack Swift*.
. Select an option under with the following data format:
+
* *Native*: A compressed format readable only by NetApp Element software-based storage systems.
* *Uncompressed*: An uncompressed format compatible with other systems.

. Enter the details:
+
* *URL*: Enter a URL to use to access the object store.
* *User name*: Enter user name for the account.
* *Authentication key*: Enter the authentication key for the account.
* *Container*: Enter the container in which to store the backup.
* *Prefix*: (Optional) Enter a prefix for the backup volume name.
* *Nametag*: (Optional) Enter a name tag to append to the prefix.

. Click *OK*.

=== Back up a volume snapshot to a cluster running Element software
You can back up a volume snapshot that resides on a cluster running NetApp Element software to a remote Element cluster.

.Before you begin
You must create a volume on the destination cluster of equal or greater size to the snapshot you are using for the backup.

.About this task
When you back up or restore from one cluster to another, the system generates a key to be used as authentication between the clusters. This bulk volume write key enables the source cluster to authenticate with the destination cluster, providing security when writing to the destination volume. As part of the backup or restore process, you need to generate a bulk volume write key from the destination volume before starting the operation.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Management*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. Click the *volumes* sub-tab.
. Check the destination volume.
. Click *Actions*.
. In the resulting menu, select *Restore from*.
. In the dialog under *Restore from*, select *NetApp Element*.
. Select an option under with the following data format:
+
* *Native*: A compressed format readable only by NetApp Element software-based storage systems.
* *Uncompressed*: An uncompressed format compatible with other systems.

. Click *Generate Key* to generate a bulk volume write key for the destination volume.
. Copy the bulk volume write key to your clipboard to apply to later steps on the source cluster.
. From the vCenter that contains the source cluster, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Check the snapshot you are using for the backup.
. Click *Actions*.
. In the resulting menu, click *Backup to*.
. In the dialog box under *Back up volume to*, select *NetApp Element*.
. Select the same option as the destination cluster under *with the following data format*.
. Enter the details:
+
* *Remote cluster MVIP*: Enter the management virtual IP address of the destination volume's cluster.
* *Remote cluster user password*: Enter the remote cluster user name.
* *Remote user password*: Enter the remote cluster password.
* *Bulk volume write key*: Paste the key you generated on the destination cluster earlier.
. Click *OK*.

== Delete a volume snapshot
You can delete a volume snapshot from a cluster running NetApp Element software using the NetApp Element Management extension point. When you delete a snapshot, the system immediately removes it.

.About this task
You can delete snapshots that are being replicated from the source cluster. If a snapshot is syncing to the target cluster when you delete it, the sync replication completes and the snapshot is deleted from the source cluster. The snapshot is not deleted from the target cluster.

You can also delete snapshots that have been replicated to the target from the target cluster. The deleted snapshot is kept in a list of deleted snapshots on the target until the system detects that you have deleted the snapshot on the source cluster. After the target has detected that you have deleted the source snapshot, the target stops replication of the snapshot.

.Steps
. From the vCenter Plug-in, select *NetApp Element Management* > *Protection*.
+
NOTE: If two or more clusters are added, ensure that the cluster that you intend to use is selected in the navigation bar.

. From the *Snapshots* sub-tab, select one of the following views:
+
* *Individual*: A list of volume snapshots that are not part of a group snapshot.
* *Inactive*: A list of volume snapshots that were created from volumes that have been deleted but not yet purged.

. Check the volume snapshot you want to delete.
. Click *Actions*.
. In the resulting menu, select *Delete*.
. Confirm the action.


[discrete]
== Find more information
*	http://mysupport.netapp.com/hci/resources[NetApp HCI Resources page^]
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
