---
sidebar: sidebar
permalink: vcp_concept_accounts.html
summary:
keywords: netapp, vcp, element, plugin, plug-in, account
---

= User accounts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
User accounts control access to the storage resources on a NetApp Element software-based network. At least one user account is required before a volume can be created.

When you create a volume, it is assigned to an account. If you have created a virtual volume, the account is the storage container. The account contains the CHAP authentication required to access the volumes assigned to it. 

An account can have up to two thousand volumes assigned to it, but a volume can belong to only one account.

User accounts can be managed from NetApp Element Management extension point.

For details, see SolidFire and Element 12.0 Documentation Center.  *FIX LINK to VCP TOPIC*

[discrete]
== Find more information
*	http://mysupport.netapp.com/hci/resources[NetApp HCI Resources page^]
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
