---
sidebar: sidebar
permalink: vcp_task_create_manage_access_groups_5_0.html
summary: You can create and manage volume access groups using the plug-in.
keywords: netapp, storage, access groups, vcp, vcenter, element
---

= Create and manage volume access groups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
A link:https://docs.netapp.com/us-en/hci/docs/concept_hci_volume_access_groups.html[volume access group^] is a collection of volumes that users can access using either iSCSI initiators or FC initiators.

You can create access groups by mapping iSCSI initiator IQNs or FC WWPNs in a collection of volumes. Each IQN that you add to an access group can access each volume in the group without requiring CHAP authentication. Each WWPN that you add to an access group enables FC network access to the volumes in the access group.

.Options
* <<Create an access group>>
* <<Edit an access group>>
* <<Add volumes to an access group>>
* <<Remove volumes from an access group>>
* <<Delete an access group>>

== Create an access group
You can create volume access groups with one or more initiators. Mapping Fibre Channel (WWPN) or iSCSI (IQN) client initiators to the volumes in a volume access group enables secure data I/O between a network and a volume.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Access Groups* sub-tab.
. Select *Create Access Group*.
. Enter a name for the volume access group.
+
TIP: Use descriptive naming best practices. This is especially important if multiple clusters or vCenter Servers are used in your environment.

. Select an unassigned IQN or WWPN from the *Select an Initiator* drop-down list and click *Add Initiator*.
+
NOTE: Initiators may be added or deleted after the volume access group has been created.

. Click *OK* to create the access group.

== Edit an access group
You can edit volume access group names or add or remove initiators from the NetApp Element Remote Plugin extension point.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Access Groups* sub-tab.
. Select the check box for the volume access group you want to edit.
. Select *Actions*.
. In the resulting menu, select *Edit*.
. Change the following as required:
.. Modify the access group name.
.. Add or remove initiators.
+
NOTE: If you are removing an initiator, click the trash icon to remove it. When you remove the initiator, it can no longer access the volumes in that volume access group. Normal account access to the volume is not disrupted.

. Select *OK*.

== Add volumes to an access group

You can add volumes to a volume access group. Each volume can belong to more than one volume access group; you can see the groups that each volume belongs to from the Active volumes view.

.What you'll need

* At least one cluster must be added and running.
* At least one access group exists.
* At least one active volume exists.

.Steps

. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Volumes* subtab.
. Select the check box for each volume that you want to add to an access group.
. Select *Actions*.
. Select *Add to Access Group*.
. Confirm the details and select a volume access group from the list.
. Select *OK*.

== Remove volumes from an access group

You can remove volumes from an access group.

When you remove a volume from an access group, the group no longer has access to that volume.

IMPORTANT: Removing a volume from an access group can disrupt host access to the volume.

. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Volumes* subtab.
. Select the check box for each volume that you want to remove from an access group.
. Select *Actions*.
. Select *Remove from Access Group*.
. Confirm the details and select the volume access group that you no longer want to have access to each selected volume.
. Select *OK*.

== Delete an access group
You can delete volume access groups using the NetApp Element Remote Plugin extension point. You do not need to delete initiator IDs or disassociate volumes from the volume access group prior to deleting the group. After you delete the access group, group access to the volumes is discontinued.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Access Groups* sub-tab.
. Select the check box for the access group you want to delete.
. Select *Actions*.
. In the resulting menu, select *Delete*.
. Confirm the action.

== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
