---
sidebar: sidebar
permalink: vcp_concept_linkedmode.html
summary:
keywords: netapp, vcp, element, plugin, plug-in, linked mode
---

= Linked mode and the plug-in
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the NetApp Element Plug-in for vCenter Server to manage cluster resources from other vCenter Servers using vCenter Linked Mode.

You can only manage the storage cluster in the Element Plug-in when you are logged in to the destination vCenter web client.

Use the following procedure to set up storage cluster management in a vSphere Linked Mode environment.

.Steps
.	Register the plug-in with each vCenter Server in the Linked Mode environment that will be using the plug-in.
. Log in once to the vSphere Web Client for each linked vCenter Server.
+
Logging in initiates installation of the plug-in on the web client.
. Log in to the web client of the destination vCenter that you want to manage the storage cluster.
.	Add the storage cluster to the Element Plug-in inventory.
+
For example, if you have vCenter1 and vCenter2 in Linked Mode and storage cluster1 and storage cluster2 and you want vCenter1 to manage cluster1 and vCenter2 to manage cluster2, you perform the following steps:
+
.. Log in to the vCenter1 web client.
.. Add cluster1 to the VCP inventory to manage cluster1 from the vCenter1 web client.
.. Log in to the vCenter2 web client.
.. Add cluster2 to the VCP inventory to manage cluster2 from the vCenter2 web client.

[discrete]
== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element software documentation^]
