---
sidebar: sidebar
permalink: vcp_task_reports_volume_performance.html
summary: You can view performance information for all volumes in the selected cluster from the Volume Performance page on the Reporting tab of the NetApp Element Plug-in for vCenter Server.
keywords: netapp, hci, vcp, vcenter, element, monitor, report, event, log, cluster, performance
---

= Monitor volume performance
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can view performance information for all volumes in the selected cluster from Reporting tab of the NetApp Element Management extension point.

.Steps

. From the vCenter Plug-in, select *NetApp Element Management*.
. Select *Reporting* > *Volume Performance*.
. To change how often the data refreshes on the page, click *Refresh every list* and choose a value.
+
The default refresh interval is 10 seconds if the cluster has less than 1000 volumes; otherwise, the default is 60 seconds. If you choose a value of Never, automatic page refreshing is disabled.

== Volume performance data

* *Name*: Name of the volume when it was created.
* *Account*: The name of the account assigned to the volume.
* *Access Groups*: The name of the volume access group or groups to which the volume belongs.
* *Volume Utilization %*: A percentage value that describes how much the client is using the volume.
+
Possible values:
* 0 = Client is not using the volume
* 100 = Client is using the max
* >100 = Client is using the burst

* *Total IOPS*: The total number of IOPS (read and write) currently being executed against the volume.
* *Read IOPS*: The total number of read IOPS currently being executed against the volume.
* *Write IOPS*: The total number of write IOPS currently being executed against the volume.
* *Total Throughput*: The total amount of throughput (read and write) currently being executed against the volume.
* *Read Throughput*: The total amount of read throughput currently being executed against the volume.
* *Write Throughput*: The total amount of write throughput currently being executed against the volume.
* *Total Latency (ms)*: The average time, in microseconds, to complete read and write operations to a volume.
* *Read Latency (ms)*: The average time, in microseconds, to complete read operations to the volume in the last 500 milliseconds.
* *Write Latency (ms)*: The average time, in microseconds, to complete write operations to a volume in the last 500 milliseconds.
* *Queue Depth*: The number of outstanding read and write operations to the volume.
* *Average IO Size*: Average size in bytes of recent I/O to the volume in the last 500 milliseconds.

== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
