---
sidebar: sidebar
permalink: vcp_task_create_manage_initiators_5_0.html
summary: You can create and manage initiators using the plug-in.
keywords: netapp, storage, inititators, vcp, vcenter, element
---

= Create and manage initiators
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Initiators enable external clients access to volumes in a cluster, serving as the entry point for communication between clients and volumes.

You can create, edit, and delete initiators, and give them friendly aliases to simplify administration and volume access. When you add an initiator to a volume access group, that initiator enables access to all volumes in the group.

.Options
* <<Create an initiator>>
* <<Edit an initiator>>
* <<Add initiators to an access group>>
* <<Delete an initiator>>

== Create an initiator
You can create iSCSI or Fibre Channel initiators and optionally assign them aliases.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Initiators* sub-tab.
. Select *Create Initiator*.
. To create a single initiator:
.. Select *Create a Single Initiator*.
.. Enter the IQN or WWPN for the initiator in the *IQN/WWPN* field.
+
The accepted format of an initiator IQN is `iqn.yyyy-mm` where y and m are digits followed by text that must only contain digits, lower-case alphabetic characters, a period (`.`), colon (`:`), or dash (`-`).
A sample of the format is as follows:
+
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
The accepted format of a Fibre Channel initiator WWPN is `:Aa:bB:CC:dd:11:22:33:44` or `AabBCCdd11223344`.
A sample of the format is as follows:
+
----
5f:47:ac:c0:5c:74:d4:02
----

.. Enter a friendly name for the initiator in the *Alias* field.
. To create multiple initiators:
.. Select *Create Multiple Initiators*.
.. Do one of the following:
*** Click *Scan Hosts* to scan vSphere hosts for initiator values not defined in the NetApp Element cluster.
*** Enter a list of IQNs or WWPNs in the text box, and select *Add Initiators*.
.. (Optional) Under the *Alias* heading, select the field for each entry to add an alias.
.. (Optional) Remove an initiator from the list, as required.
. Click *OK* to create the initiator.

== Edit an initiator
You can change the alias of an existing initiator or add an alias if one does not already exist.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Initiators* sub-tab.
. Select the check box for the initiator you want to edit.
. Select *Actions*.
. In the resulting menu, select *Edit*.
. Enter a new alias for the initiator in the *Alias* field.
. Click *OK*.

== Add initiators to an access group
You can add initiators to an access group to allow access to volumes in the volume access group without requiring CHAP authentication. When you add an initiator to a volume access group, the initiator has access to all volumes in that volume access group.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Initiators* sub-tab.
. Select the check boxes for the initiators you want to add to an access group.
. Select *Actions*.
. In the resulting menu, select *Add to Access Group*.
. In the *Add to Access Group* dialog box, choose an access group from the drop-down list.
. Click *OK*.

== Delete an initiator
You can delete an initiator after it is no longer needed. When you delete an initiator, the system removes it from any associated volume access group. Any connections using the initiator remain valid until the connection is reset.

.Steps
. Select *NetApp Element Remote Plugin > Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Initiators* sub-tab.
. Select the check box for the initiators you want to delete.
. Select *Actions*.
. In the resulting menu, select *Delete*.
. Confirm the action.

== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
