---
sidebar: sidebar
permalink: vcp_task_restart_node.html
summary: You can restart an active node in the cluster using the plug-in.
keywords: netapp, nodes, restart, details, vcp, vcenter, element
---

= Restart a node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can restart one or more active nodes in a cluster using the NetApp Element Management extension point.

.What you'll need
You have stopped I/O and disconnected all iSCSI sessions if you are restarting more than one node simultaneously.

.About this task
To restart the cluster, you can select all cluster nodes and perform a restart.

CAUTION: This method restarts all networking services on a node, causing temporary loss of networking connectivity.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. Select *NetApp Element Management > Cluster*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Nodes* sub-tab.
.. From the *Active* view, select the check box for each node you want to restart.
.. Click *Actions*.
.. Select *Restart*.
. Confirm the action.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
