---
sidebar: sidebar
permalink: vcp_concept_protection_domains.html
summary:
keywords: netapp, vcp, element, plugin, plug-in, protection, domain
---

= Protection domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A protection domain is a node or a set of nodes grouped together such that any node or all nodes in
the domain might fail without causing the cluster to lose data availability. The protection domains feature allows you to monitor a cluster's resource capacity to ensure the cluster is still capable of healing from a failure event. You can select monitoring at either a node or chassis domain level:

* *Node level* defines each protection domain per individual node, with each node potentially located across chassis.
* *Chassis level* defines each protection domain by nodes that share a chassis.

A chassis domain requires more potential capacity resources than a node domain to be resilient to failure. When a protection domain threshold is exceeded, a cluster no longer has sufficient capacity to heal from failure while also maintaining undisrupted data availability.

[discrete]
== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
