---
sidebar: sidebar
permalink: vcp_concept_protection_domains.html
summary:
keywords: netapp, vcp, element, plugin, plug-in, protection, domain
---

= Protection domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
A protection domain is a node or a set of nodes grouped together such that any part or even all of it might fail, while maintaining data availability. Protection domains enable a storage cluster to heal automatically from the loss of a chassis (chassis affinity) or an entire domain (group of chassis).

A protection domain layout assigns each node to a specific protection domain.

Two different protection domain layouts, called protection domain levels, are supported.

* At the node level, each node is in its own protection domain.
* At the chassis level, only nodes that share a chassis are in the same protection domain.
** The chassis level layout is automatically determined from the hardware when the node is added to the cluster.
** In a cluster where each node is in a separate chassis, these two levels are functionally identical.

You can manually enable protection domain monitoring using the NetApp Element Configuration extension point in the NetApp Element Plug-in for vCenter Server. You can select a protection domain threshold based on node or chassis domains.

When creating a new cluster, if you are using storage nodes that reside in a shared chassis, consider designing for chassis-level failure protection using the protection domains feature.

You can define a custom protection domain layout, where each node is associated with one and only one custom protection domain. By default, each node is assigned to the same default custom protection domain.

For details, see SolidFire and Element 12.0 Documentation Center.  *FIX LINK to VCP TOPIC*

[discrete]
== Find more information
*	http://mysupport.netapp.com/hci/resources[NetApp HCI Resources page^]
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
