---
sidebar: sidebar
permalink: vcp_task_configure_manage_vvols.html
summary: You can set up virtual volumes for provisioned storage in your cluster.
keywords: netapp, set up vvol, configure vvol, virtual volume, vcp, vcenter, element
---

= Configure and manage virtual volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can view information and perform tasks for virtual volumes and their associated storage containers, protocol endpoints, bindings, and hosts from the NetApp Element Management extension point. You must enable Virtual Volume functionality for it to be available on the cluster.

=== Setup tasks:
. <<Enable virtual volumes functionality>>
. <<Register the VASA provider>>
. <<Create a storage container and associated VVol datastore>>

=== Management tasks:
* <<Monitor virtual volume resources>>
--VVOL
--Storage container
-Protocol endpoints
* <<Delete a storage container>>

== Enable virtual volumes functionality

== Register the VASA provider

== Create a storage container and associated VVol datastore


.Steps
. Select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Configure*.
. In the *Configure QoSSIOC Settings* dialog box, enter the following information:
* *mNode IP Address/FQDN*: The IP address of the management node for the cluster that contains the QoSSIOC service.
* *mNode Port*: The port address for the management node that contains the QoSSIOC service. The default port is 8443.
* *QoSSIOC User ID*: The user ID for the QoSSIOC service. The QoSSIOC service default user ID is admin. For NetApp HCI, the user ID is the same one entered during installation using the NetApp Deployment Engine.
* *QoSSIOC Password*: The password for the Element QoSSIOC service. The QoSSIOC service default password is `solidfire`. If you have not created a custom password, you can create one from the registration utility UI (`https://[management node IP]:9443`).
+
NOTE: For NetApp HCI deployments, the default password is randomly generated during installation. To determine the password, see procedure 4 in this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] article.

* *vCenter User ID*: The user name for the vCenter admin with full Administrator role privileges.
* *vCenter Password*: The password for the vCenter admin with full Administrator role privileges.
. Click *OK*.
The *QoSSIOC Status* field displays `UP` when the plug-in can successfully communicate with the service.
+
NOTE: See this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] to troubleshoot if the status is any of the following:
* `Down`: QoSSIOC is not enabled.
* `Not Configured`: QoSSIOC settings have not been configured.
* `Network Down`: vCenter cannot communicate with the QoSSIOC service on the network. The mNode and SIOC service might still be running.

+
After the QoSSIOC service is enabled, you can configure QoSSIOC performance on individual datastores.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
