---
sidebar: sidebar
permalink: vcp_task_qossioc.html
summary: You can set up and modify volume QoS and datastore SIOC (QoSSIOC) for provisioned storage in your cluster.
keywords: netapp, qossioc, quality of service, qos, sioc, vcp, vcenter, element
---

= Set up and manage QoSSIOC for Element volumes and VMware datastores
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can set up QoSSIOC for individual volumes and datastores controlled by the plug-in. QoSSIOC is automatic quality of service (QoS) based on storage I/O control (SIOC) settings of all VMs on a standard datastore.

The QoSSIOC service on the management node communicates with vCenter and monitors VM activity on datastores. QoSSIOC adjusts QoS values on standard Element volumes when virtual machine events occur, such as power on or power off events, guest restarts or shutdown, or reconfiguration activity. QoSSIOC is an optional feature and is not required for the plug-in to manage storage clusters.

QoSSIOC is available only with standard datastores. It does not work with virtual volumes (VVols).

NOTE: You cannot enable virtual volumes (VVols) functionality or make VVols available to vSphere using the QoSSIOC Settings page. See Element Plug-in for vCenter Server documentation about configuring VVols functionality for more information.

For Linked Mode, the NetApp Element Plug-in for vCenter Server registers all vCenter Servers using the QoSSIOC settings you provide on a single vCenter Server.

Using the vCenter Plug-in, you can configure and manage QoSSIOC by completing the following tasks:

* <<Configure QoSSIOC settings>>
* <<Edit QoSSIOC settings>>
* <<Clear QoSSIOC settings>>
* <<Change the QoSSIOC service password>>

== Configure QoSSIOC settings
You can configure QoSSIOC and vCenter credentials that will enable the QoSSIOC service to communicate with vCenter. After the QoSSIOC service is enabled, you can configure QoSSIOC performance on individual datastores.

.About this task
After you have configured valid QoSSIOC settings for the management node, these settings become the default. The QoSSIOC settings revert to the last known valid QoSSIOC settings until you provide valid QoSSIOC settings for a new management node. You must clear the QoSSIOC settings for the configured management node before setting the QoSSIOC credentials for a new management node.

.Steps
. Select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Configure*.
. In the *Configure QoSSIOC Settings* dialog box, enter the following information:
* *mNode IP Address/FQDN*: The IP address of the management node for the cluster that contains the QoSSIOC service.
* *mNode Port*: The port address for the management node that contains the QoSSIOC service. The default port is 8443.
* *QoSSIOC User ID*: The user ID for the QoSSIOC service. The QoSSIOC service default user ID is admin. For NetApp HCI, the user ID is the same one entered during installation using the NetApp Deployment Engine.
* *QoSSIOC Password*: The password for the Element QoSSIOC service. The QoSSIOC service default password is `solidfire`. If you have not created a custom password, you can create one from the registration utility UI (`https://[management node IP]:9443`).
+
NOTE: For NetApp HCI deployments, the default password is randomly generated during installation. To determine the password, see procedure 4 in this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] article.

* *vCenter User ID*: The user name for the vCenter admin with full Administrator role privileges.
* *vCenter Password*: The password for the vCenter admin with full Administrator role privileges.
. Click *OK*.
The *QoSSIOC Status* field displays `UP` when the plug-in can successfully communicate with the service.
+
NOTE: See this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] to troubleshoot if the status is any of the following:
* `Down`: QoSSIOC is not enabled.
* `Not Configured`: QoSSIOC settings have not been configured.
* `Network Down`: vCenter cannot communicate with the QoSSIOC service on the network. The mNode and SIOC service might still be running.

== Edit QoSSIOC settings
You can change the QoSSIOC and vCenter credentials of an active Element management node.

.Steps
. Select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Edit*.
. In the *Edit QoSSIOC Settings* dialog box, change any of the following:
* *QoSSIOC User ID*: The user ID for the QoSSIOC service. The QoSSIOC service default user ID is `admin`. For NetApp HCI, the user ID is the same one entered during installation using the NetApp Deployment Engine.
* *QoSSIOC Password*: The password for the Element QoSSIOC service. The QoSSIOC service default password is `solidfire`. If you have not created a custom password, you can create one from the registration utility UI (`https://[management node IP]:9443`).
+
NOTE: For NetApp HCI deployments, the default password is randomly generated during installation. To determine the password, see procedure 4 in this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] article.

* *vCenter User ID*: The user name for the vCenter admin with full Administrator role privileges.
* *vCenter Password*: The password for the vCenter admin with full Administrator role privileges.
. Click *OK*.
The QoSSIOC Status field displays `UP` when the plug-in can successfully communicate with the service.
+
NOTE: See this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] to troubleshoot if the status is any of the following:
* `Down`: QoSSIOC is not enabled.
* `Not Configured`: QoSSIOC settings have not been configured.
* `Network Down`: vCenter cannot communicate with the QoSSIOC service on the network. The
mNode and SIOC service might still be running.

+
NOTE: After you have configured valid QoSSIOC settings for the management node, these settings become the default. The QoSSIOC settings revert to the last known valid QoSSIOC settings until you provide valid QoSSIOC settings for a new management node. You must clear the QoSSIOC settings for the configured management node before setting the QoSSIOC credentials for a new management node.

== Clear QoSSIOC settings
You can clear the QoSSIOC configuration details for the Element storage management node (mNode). You must clear the settings for the configured management node before configuring the credentials for a new management node or changing the QoSSIOC service password. Clearing the QoSSIOC settings removes active QoSSIOC from the vCenter, cluster, and datastores.

.Steps
. Select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Clear*.
. Confirm the action.
+
The *QoSSIOC Status* field displays `Not Configured` after the process is complete.

== Change the QoSSIOC service password
You can change the password for the QoSSIOC service on the management node using the registration utility UI.

.What you'll need
* Your management node is powered on.

.About this task
This process describes how to change the QoSSIOC password only. If you want to change the QoSSIOC user name, you can do so from the <<Configure QoSSIOC settings, QoSSIOC Settings>> page of the NetApp Element Configuration extension point.

.Steps
. Select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Clear*.
. Confirm the action.
+
The *QoSSIOC Status* field displays `Not Configured` after the process is complete.

. Enter the IP address for your management node in a browser, including the TCP port for registration: `https://[management node IP]:9443`.
+
The registration utility UI displays the *Manage QoSSIOC Service Credentials* page for the plug-in.
+
GRAPHIC HERE!!!!!!

. Enter the following information:
.. `Old Password`: The current password of the QoSSIOC service. If you have not yet assigned a password, type the default password of `solidfire`.
+
NOTE: For NetApp HCI deployments, the default password is randomly generated during installation. To determine the password, see procedure 4 in this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] article.

.. *New Password*: The new password for the QoSSIOC service.
.. *Confirm Password*: Enter the new password again.
. Click *Submit Changes*.
+
NOTE: The QoSSIOC service automatically restarts after you submit changes.

. In your vSphere Web Client, select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Configure*.
. In the *Configure QoSSIOC Settings* dialog box, enter the new password in the *QoSSIOC
Password* field.
. Click *OK*.
+
The *QoSSIOC Status* field displays `UP` when the plug-in can successfully communicate with
the service.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
