---
sidebar: sidebar
permalink: vcp_task_create_manage_user_accounts.html
summary: You can create and manage user accounts using the plug-in.
keywords: netapp, storage, accounts, vcp, vcenter, element
---

= Create and manage user accounts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
link:vcp_concept_accounts.html[User accounts^] are used to control access to the storage resources on a NetApp Element software-based network.

.Options
* <<Create an account>>
* <<Edit an account>>
* <<Delete an account>>

== Create an account
You can create a unique user account to allow access to storage volumes.

.What you'll need

* At least one cluster must be added and running.

.Steps
. Select *NetApp Element Management > Management*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Accounts* sub-tab.
. Select *Create Account*.
. Enter a user name.
+
TIP: Use descriptive naming best practices. This is especially important if multiple clusters or vCenter Servers are used in your environment.

. In the *CHAP Settings* section:
.. Enter the initiator secret for CHAP node session authentication.
.. Enter the target secret for CHAP node session authentication.
+
NOTE: Initiator and target secrets must differ. If these fields are left blank, the system generates the authentication credentials.

. Click *OK* to create the account.

== Edit an account
You can edit a user account to change the status or the CHAP secrets. Changing CHAP settings can cause lost connectivity between a host and its associated volumes.

.About this task
If you are using persistent volumes with the management node, do not modify the account name of the account associated with these volumes.

.Steps
. Select *NetApp Element Management > Management*.

+
NOTE: If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Accounts* sub-tab.
. Select the check box for the account you want to edit.
. Select *Actions*.
. In the resulting menu, select *Edit*.
. Change the following as required:
.. Edit the access status of the account.
+
IMPORTANT: Changing the access to *Locked* terminates all iSCSI connections to the account, and the account is no longer accessible. Volumes associated with the account are maintained; however, the volumes are not iSCSI-discoverable.

.. Edit the initiator secret or target secret credentials used for node session authentication.
+
NOTE: If you do not change the credentials, they remain the same. If you make the credentials fields blank, the system generates new passwords.

. Click *OK*.

== Delete an account
You can delete user accounts using the NetApp Element Management extension point.

.What you'll need
Delete and purge any volumes associated with the account or reassign the volumes to another account.

IMPORTANT: If you are using persistent volumes with the management node, do not delete the account associated with these volumes.

.Steps
. Select *NetApp Element Management > Management*.

+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Accounts* sub-tab.
. Select the check box for the account you want to delete.
. Click *Actions*.
. In the resulting menu, select *Delete*.
. Confirm the action.

== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
