---
sidebar: sidebar
permalink: vcp_task_view_node_details.html
summary: You can view detailed information about the nodes that make up your storage cluster.
keywords: netapp, nodes, view, details, vcp, vcenter, element
---

= View node details
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can view a list of the nodes in the cluster on the Nodes page of the Cluster tab from the NetApp Element Management extension point. You must select Active view to see the list of active nodes. You can change the view by selecting `Pending`, `PendingActive`, and `All` options using the drop-down filter.


.Steps
. Select *NetApp Element Management > Cluster*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Nodes* sub-tab.
. Select the *Active* view.
. View the details of the nodes in the storage cluster.
+
You can view information such as node IDs, the name and state of each node, configured IOPS, node type, the number of active drives in each node, and networking information about each node.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
