---
sidebar: sidebar
permalink: vcp_task_remove_drive.html
summary: You can remove a drive from the storage cluster using the plug-in.
keywords: netapp, drives, remove, vcp, vcenter, element
---

= Remove a drive
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can remove a drive from a cluster using the NetApp Element Management extension point. You might do this when reducing cluster capacity or preparing to replace drives nearing the end of their service life. Removing a drive takes the drive offline. Any data on the drive is removed and migrated to other drives in the cluster before the drive is removed from the cluster. The data migration to other active drives in the system can take a few minutes to an hour depending on capacity utilization and active I/O on the cluster.

.About this task
When you remove a drive in a `Failed` state, the drive is not returned to `Available` or `Active` states. Instead, the drive is unavailable for use in the cluster.

.Steps
. Select *NetApp Element Management > Cluster*.
. If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.
. Select *All* from the drop-down list to view the complete list of drives.
. Remove drives as follows:
.. Select the check box for each drive you want to remove.
.. Click *Remove Drives*.
. Confirm the action.
+
NOTE: If there is not enough capacity to remove active drives before removing a node, an error message appears when you confirm the drive removal.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
