---
sidebar: sidebar
permalink: vcp_task_clusters_manage.html
summary: You can add a node to the storage cluster using the plug-in.
keywords: netapp, cluster, vcp, vcenter, element
---

= Manage clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can edit a cluster running Element software, manage SSH configuration, set protection domain monitoring, and shut down a cluster.

.What you'll need

* At least one cluster must be added: 

** link:vcp_task_getstarted_5_0.html#add-storage-clusters-for-use-with-the-plug-in[Add a cluster using Element Plug-in for vCenter 5.0 and later]
** link:vcp_task_getstarted.html#add-storage-clusters-for-use-with-the-plug-in[Add a cluster using Element Plug-in for vCenter 4.10 and earlier]

+
NOTE: You must add at least one cluster to use the plug-in extension point functions.

* Current full Cluster Admin user credentials for the cluster.
* Firewall rules allow open network communication between the vCenter and the cluster MVIP on the following TCP ports:
** Beginning with Element Plug-in for vCenter 5.0, on ports 443, 8333, and 8443.
** For Element Plug-in for vCenter 4.10 or earlier, on ports 443 and 8443.

.Options

* <<View cluster details>>
* <<Edit a cluster profile>>
* <<Remove a cluster profile>>
* <<Enable Encryption at Rest>>
* <<Disable Encryption at Rest>>
* <<Enable SSH>>
* <<Change the SSH time limit>>
* <<Disable SSH>>
* <<Set protection domain monitoring>>
* <<Shut down a cluster>>
* <<Expand your NetApp HCI infrastructure>>

== View cluster details
You can view cluster details from the vCenter Plug-in extension point.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster you want to edit.
. Select *Actions*.
. Select *Details*.
. Review the following information for all clusters:
+
* *Cluster Name*: The name for the cluster.
* *vCenter IP Address*: The IP address or FQDN of the vCenter Server to which the cluster is assigned.
* *Unique ID*: Unique ID for the cluster.
* *Management Virtual IP*: The management virtual IP address (MVIP).
* *Storage Virtual*: The storage virtual IP address (SVIP).
* *Status*: The status of the cluster.
* *VVols*: The status of the VVols functionality on the cluster.
. Review additional details for an individual cluster:
+
* *MVIP Node ID*: The node that holds the master MVIP address.
* *SVIP Node ID*: The node holding the master SVIP address.
* *Element Version*: The version of NetApp Element software that the cluster is running.
* *VASA 2 Status*: The status of the VASA Provider on Element cluster.
* *VASA Provider URL*: The URL of the VASA Provider enabled on the Element cluster, when applicable.
* *Encryption At Rest Status*: Possible values:
+
** Enabling: Encryption at Rest is being enabled.
** Enabled: Encryption at Rest is enabled.
** Disabling: Encryption at Rest is being disabled.
** Disabled: Encryption at Rest is disabled.
* *Ensemble Nodes*: IPs of the nodes that are part of the database ensemble.
* *Paired With*: The names of additional clusters that are paired with the local cluster.
* *SSH Status*: The status of the secure shell. If enabled, the time remaining is displayed.


== Edit a cluster profile
You can change the cluster User ID and password from the plug-in extension point.

NOTE: This procedure describes how to change the cluster admin user name and password used by the plug-in. You cannot change the cluster admin credentials from the plug-in. See https://docs.netapp.com/us-en/element-software/storage/concept_system_manage_manage_cluster_administrator_users.html[managing cluster administrator user accounts^] for instructions on changing credentials for a cluster administrator account.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Edit*.
. Change any of the following:
+
* User ID: The cluster administrator name.
* Password: The cluster administrator password.
+
NOTE: You cannot change the IP address or FQDN of a cluster after a cluster is added. You also cannot change the assigned Linked Mode vCenter Server for an added cluster. To change the cluster address or associated vCenter Server, you must remove the cluster and add it again.

. Select *OK*.

== Remove a cluster profile
You can remove the profile of a cluster that you no longer want to manage from the vCenter Plug-in using the plug-in extension point.

If you set up a Linked Mode group and want to reassign a cluster to another vCenter Server, you can remove the cluster profile and add it again with a different linked vCenter Server IP.

[NOTE]
====
* Beginning with Element vCenter plug-in 5.0, to use link:vcp_concept_linkedmode.html[vCenter Linked Mode], you register the Element Plug-in from a separate management node for each vCenter Server that manages NetApp SolidFire storage clusters. 
* Using Element vCenter plug-in 4.10 and earlier to manage cluster resources from other vCenter Servers using link:vcp_concept_linkedmode.html[vCenter Linked Mode] is limited to local storage clusters only.
====

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster you want to remove.
. Select *Actions*.
. Select *Remove*.
. Confirm the action.

== Enable Encryption at Rest
You can manually enable encryption at rest (EAR) functionality using the plug-in extension point.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Select the cluster on which you want to enable encryption at rest.
. Select *Actions*.
. In the resulting menu, select *Enable EAR*.
. Confirm the action.

== Disable Encryption at Rest
You can manually disable encryption at rest (EAR) functionality using the plug-in extension point.

.Steps
. In your vSphere Web Client, open the *Clusters* tabb:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Select the check box for the cluster.
. Select *Actions*.
. In the resulting menu, select *Disable EAR*.
. Confirm the action.

== Enable SSH

You can manually enable a Secure Shell (SSH) session using the plug-in extension point. Enabling SSH allows NetApp technical support engineers access to storage nodes for troubleshooting for the duration you determine.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Enable SSH*.
. Enter a duration for the SSH session to be enabled in hours up to a maximum of 720.
+
NOTE: To continue, you need to enter a value.

. Select *Yes*.


== Change the SSH time limit

You can enter a new duration for an SSH session.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Change SSH*.
+
The dialog box displays the remaining time for the SSH session.

. Enter a new duration for the SSH session in hours up to a maximum of 720.
+
NOTE: To continue, you need to enter a value.

. Select *Yes*.

== Disable SSH
You can manually disable Secure Shell (SSH) access to nodes in the storage cluster using the plug-in extension point.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Disable SSH*.
. Select *Yes*.

== Set protection domain monitoring
You can manually enable link:vcp_concept_protection_domains.html[protection domain monitoring] using the plug-in extension point. You can select a protection domain threshold based on node or chassis domains.

.What you'll need

* The selected cluster must be monitored by Element 11.0 or later to use protection domain monitoring; otherwise, protection domain functions are not available.
* Your cluster must have more than two nodes to use the protection domains feature. Compatibility with two-node clusters is not available.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Set Protection Domain Monitoring*.
. Select a failure threshold:
+
* *Node*: The threshold beyond which a cluster can no longer provide uninterrupted data during hardware failures at the node level. The node threshold is the system default.
* *Chassis*: The threshold beyond which a cluster can no longer provide uninterrupted data during hardware failures at the chassis level.

. Select *OK*.

After you have set monitoring preferences, you can monitor protection domains from the link:vcp_task_reports_overview.html#reporting-overview-page-data[Reporting] tab of the NetApp Element Management extension point.

== Shut down a cluster
You can manually shut down all active nodes in a storage cluster using the plug-in extension point.

If you want to link:vcp_task_add_manage_nodes.html#restart-a-node[restart] rather than shut down the cluster, you can select all nodes from the Cluster page in the NetApp Element Management extension point and perform a restart.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.What you'll need
You have stopped I/O and disconnected all iSCSI sessions.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Shutdown*.
. Confirm the action.


== Expand your NetApp HCI infrastructure
You can manually expand your NetApp HCI infrastructure by adding nodes using NetApp HCI. A link to a NetApp HCI UI for scaling your system is provided from the plug-in extension point. 

Additional links are provided from the Getting Started and Cluster pages:

* Beginning with Element vCenter plug-in 5.0, select NetApp Element Remote Plugin > Management.
* For Element vCenter plug-in 4.10 and earlier, select the NetApp Element Management extension point.

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. In your vSphere Web Client, open the *Clusters* tab:
+
* Beginning with Element vCenter plug-in 5.0, select *NetApp Element Remote Plugin > Configuration > Clusters*.
* For Element vCenter plug-in 4.10 and earlier, select *NetApp Element Configuration > Clusters*.
. Check the cluster.
. Select *Actions*.
. Select *Expand your NetApp HCI*.

== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
