---
sidebar: sidebar
permalink: vcp_concept_linkedmode.html
summary:
keywords: netapp, vcp, element, plugin, plug-in, linked mode
---

= Linked mode and the plug-in
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the NetApp Element Plug-in for vCenter Server to manage cluster resources from other vCenter Servers using vCenter Linked Mode.

NOTE: Using vCenter Linked Mode is not supported for NetApp Element vCenter plug-in 5.0. If your vCenter Server is version 5.0, see the link:vcp_concept_remote_plugin_extension_point.html[NetApp Element Remote Plugin] documentation.

You can only manage the storage cluster in the Element Plug-in when you are logged in to the destination vCenter web client.

To set up storage cluster management in a vSphere Linked Mode environment, you can use the following procedure to manually add the storage clusters.

.Steps
.	Register the plug-in with each vCenter Server in the Linked Mode environment that will be using the plug-in.
. Log in once to the vSphere Web Client for each linked vCenter Server.
+
Logging in initiates installation of the plug-in on the web client.
. Log in to the web client of the destination vCenter that you want to manage the storage cluster.
.	Add the storage cluster to the Element Plug-in inventory.

.Example
You have vCenter1 and vCenter2 in Linked Mode and storage cluster1 and storage cluster2. You want vCenter1 to manage cluster1 and vCenter2 to manage cluster2. To set up the storage cluster management, after registering the plug-in with each vCenter Server, you perform the following steps:

. Log in to the vCenter1 web client.
. To manage cluster1 from the vCenter1 web client, add cluster1 to the Element Plug-in inventory.
. Log in to the vCenter2 web client.
. To manage cluster2 from the vCenter2 web client, add cluster2 to the Element Plug-in inventory.

[discrete]
== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
*	https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
