---
sidebar: sidebar
permalink: vcp_task_shut_down_node.html
summary: You can shut down an active node in the cluster using the plug-in.
keywords: netapp, nodes, shut down, details, vcp, vcenter, element
---

= Shut down a node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can shut down one or more active nodes in a cluster using the NetApp Element Management extension point. To shut down the cluster, you can select all cluster nodes and perform a simultaneous shutdown.

.What you'll need
You have stopped I/O and disconnected all iSCSI sessions if you are restarting more than one node simultaneously.

.About this task

NOTE: This feature is unavailable in SolidFire Enterprise SDS clusters.

.Steps
. Select *NetApp Element Management > Cluster*.
+
NOTE:  If two or more clusters are added, ensure that the cluster you intend to use for the task is selected in the navigation bar.

. Select the *Nodes* sub-tab.
.. From the *Active* view, select the check box for each node you want to shut down.
.. Click *Actions*.
.. Select *Shutdown*.
. Confirm the action.

NOTE: If a node has been down longer than 5.5 minutes under any type of shutdown condition, the NetApp Element software determines that the node is not coming back to join the cluster. Double Helix data protection begins the task of writing single replicated blocks to another node to replicate the data. Depending on the length of time a node is shut down, its drives might need to be added back to the cluster after the node is brought back online.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
