---
sidebar: sidebar
permalink: vcp_task_configure_qossioc.html
summary: You can set up volume QoS and datastore SIOC (QoSSIOC) for provisioned storage in your cluster.
keywords: netapp, set up qossioc, configure qos, quality of service, qos, sioc, vcp, vcenter, element
---

= Configure QoSSIOC settings
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can configure QoSSIOC and vCenter credentials that will enable the QoSSIOC service to communicate with vCenter. link:vcp_task_configure_qossioc.html[QoSSIOC] is automatic quality of service (https://docs.netapp.com/us-en/hci/docs/concept_hci_performance.html[QoS^]) based on Storage I/O Control (https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-7686FEC3-1FAC-4DA7-B698-B808C44E5E96.html[SIOC]) settings of all VMs on a standard datastore

.About this task
After you have configured valid QoSSIOC settings for the management node, these settings become the default. The QoSSIOC settings revert to the last known valid QoSSIOC settings until you provide valid QoSSIOC settings for a new management node. You must clear the QoSSIOC settings for the configured management node before setting the QoSSIOC credentials for a new management node.

.Steps
. Select *NetApp Element Configuration > QoSSIOC Settings*.
. Click *Actions*.
. In the resulting menu, select *Configure*.
. In the *Configure QoSSIOC Settings* dialog box, enter the following information:
* *mNode IP Address/FQDN*: The IP address of the management node for the cluster that contains the QoSSIOC service.
* *mNode Port*: The port address for the management node that contains the QoSSIOC service. The default port is 8443.
* *QoSSIOC User ID*: The user ID for the QoSSIOC service. The QoSSIOC service default user ID is admin. For NetApp HCI, the user ID is the same one entered during installation using the NetApp Deployment Engine.
* *QoSSIOC Password*: The password for the Element QoSSIOC service. The QoSSIOC service default password is `solidfire`. If you have not created a custom password, you can create one from the registration utility UI (`https://[management node IP]:9443`).
+
NOTE: For NetApp HCI deployments, the default password is randomly generated during installation. To determine the password, see procedure 4 in this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] article.

* *vCenter User ID*: The user name for the vCenter admin with full Administrator role privileges.
* *vCenter Password*: The password for the vCenter admin with full Administrator role privileges.
. Click *OK*.
The *QoSSIOC Status* field displays `UP` when the plug-in can successfully communicate with the service.
+
NOTE: See this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Plug-in_for_vCenter_server/mNode_Status_shows_as_%27Network_Down%27_or_%27Down%27_in_the_mNode_Settings_tab_of_the_Element_Plugin_for_vCenter_(VCP)[KB^] to troubleshoot if the status is any of the following:
* `Down`: QoSSIOC is not enabled.
* `Not Configured`: QoSSIOC settings have not been configured.
* `Network Down`: vCenter cannot communicate with the QoSSIOC service on the network. The mNode and SIOC service might still be running.

+
After the QoSSIOC service is enabled, you can configure QoSSIOC performance on individual datastores.

[discrete]
== Find more information
*	https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
