---
sidebar: sidebar
permalink: vcp_task_protect_overview.html
summary: You can ensure that copies of your data are created and stored where you need them.
keywords: netapp, vcp, vcenter, element, protect, data
---

= Protect data with the NetApp Element Plug-in for vCenter Server
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can ensure that copies of your data are created and stored where you need them by using the NetApp Element Plug-in for vCenter Server. To do this, you can create and manage volume and group snapshots, set up snapshot schedules, and create volume and cluster pair relationships for replication between remote clusters.

.Options

* link:vcp_task_protect_snapshots_volume.html[Create and manage volume snapshots]
* link:vcp_task_protect_snapshots_group.html[Create and manage group snapshots]
* link:vcp_task_protect_snapshots_schedules.html[Create snapshot schedules]
* link:vcp_task_protect_remote_replication.html[Perform remote replication between clusters]



[discrete]
== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element software documentation^]
