---
sidebar: sidebar
permalink: vcp_concept_linkedmode.html
summary:
keywords: netapp, vcp, element, plugin, plug-in, linked mode
---

= Linked mode and the plug-in
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the NetApp Element Plug-in for vCenter Server to manage cluster resources from other vCenter Servers using vCenter Linked Mode.

You can log into any vCenter Server that is part of a Linked Mode group and manage the resources owned by other linked vCenter Servers from a single interface.

The plug-in must be registered with each vCenter Server in the Linked Mode environment that will be using the plug-in. You must complete the registration with each vCenter Server using the registration utility for the plug-in. You must also log in one time to the vSphere Web Client for each linked vCenter Server. Logging in initiates installation of the plug-in on the web client.

TIP: Manage the cluster from the vCenter Server you associate with the cluster during the Add Cluster configuration process.

Hosts that use Element software-based storage are exclusive to a particular vCenter Server and are not shared between members of a Linked Mode group. Because of this, any storage management tasks for a cluster are limited to the available hosts within a vCenter Server.


[discrete]
== Find more information
*	https://docs.netapp.com/us-en/hci/index.html[NetApp HCI Documentation^]
*	http://mysupport.netapp.com/hci/resources[NetApp HCI Resources page^]
*	https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[NetApp SolidFire and Element Documentation Center (Documentation Center Versions)^]
